name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  TEST_TAG: marcosmorelli/node-express-boilerplate:test
  LATEST_TAG: marcosmorelli/node-express-boilerplate:latest

jobs:
  Test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: test
          cache-from: type=registry,ref=${{ env.TEST_TAG }}
          cache-to: type=registry,ref=${{ env.TEST_TAG }},mode=max
          tags: ${{ env.TEST_TAG }}
          push: true
          platforms: linux/amd64,linux/arm64
      -
        name: Test
        run: |
          docker compose up test
      - 
        name: Post Test
        if: always()
        run: docker compose down
  Publish:
    needs: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build production image
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=registry,ref=${{ env.LATEST_TAG }}
          cache-to: type=registry,ref=${{ env.LATEST_TAG }},mode=max
          tags: ${{ env.LATEST_TAG }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
