services:
  node-express:
    build: .
    image: node-express-boilerplate:latest
    env_file:
      - .env.example
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-express-boilerplate
    ports:
      - '3000:3000'
    depends_on:
      mongodb:
        condition: service_healthy

  test:
    build:
      context: .
      target: test
    image: marcosmorelli/node-express-boilerplate:test
    env_file:
      - .env.example
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-express-boilerplate
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7.0.16
    container_name: mongodb
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 1s
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - dbdata:/data/db

volumes:
  dbdata:

networks:
  default:
    name: node-network
    driver: bridge