name: Node set up composite

description: Will set up Node and install all packages by caching node_modules

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'pnpm'
        
    - name: Install dependencies
      shell: bash
      run: pnpm install