name: Node set up composite

description: Will set up Node and install all packages by caching node_modules

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 9