name: Lint code

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.js'
      - '**.yaml'
      - '**.yml'
      - '.eslintignore'
      - '.eslintrc.json'
      - '.prettierignore'
      - '.prettierrc'
      # In case something like eslint or prettier upgrades
      - 'pnpm-lock.yaml'
      # In case one of the script definitions changed
      - 'package.json'

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
  
jobs:
  Linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/node-pnpm-setup

      - name: Runs prettier
        run: npm run prettier

      - name: Runs linter
        run: npm run lint
